// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getRefreshToken.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT 
    token, 
    expires_at, 
    revoked_at
FROM 
    refresh_tokens
WHERE 
    token = $1
`

type GetRefreshTokenRow struct {
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i GetRefreshTokenRow
	err := row.Scan(&i.Token, &i.ExpiresAt, &i.RevokedAt)
	return i, err
}
