// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateUserInfo.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users 
SET 
    email = $1,
    hashed_password = $2
WHERE 
    id = $3
RETURNING id, created_at, updated_at, email, hashed_password
`

type UpdateUserInfoParams struct {
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserInfo, arg.Email, arg.HashedPassword, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
