// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateUserInfo.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users 
SET 
    email = $1,
    hashed_password = $2,
    updated_at = NOW()
WHERE 
    id = $3
RETURNING id, created_at, updated_at, email, is_chirpy_red
`

type UpdateUserInfoParams struct {
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	ID             uuid.UUID `json:"id"`
}

type UpdateUserInfoRow struct {
	ID          uuid.UUID    `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Email       string       `json:"email"`
	IsChirpyRed sql.NullBool `json:"is_chirpy_red"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (UpdateUserInfoRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserInfo, arg.Email, arg.HashedPassword, arg.ID)
	var i UpdateUserInfoRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.IsChirpyRed,
	)
	return i, err
}
