// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateIsChirpyRed.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const upgradeChirpyRed = `-- name: UpgradeChirpyRed :one
UPDATE 
    users 
SET 
    is_chirpy_red = true,
    updated_at = NOW()
WHERE 
    id = $1
RETURNING 
    id, created_at, updated_at, email, is_chirpy_red
`

type UpgradeChirpyRedRow struct {
	ID          uuid.UUID    `json:"id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Email       string       `json:"email"`
	IsChirpyRed sql.NullBool `json:"is_chirpy_red"`
}

func (q *Queries) UpgradeChirpyRed(ctx context.Context, id uuid.UUID) (UpgradeChirpyRedRow, error) {
	row := q.db.QueryRowContext(ctx, upgradeChirpyRed, id)
	var i UpgradeChirpyRedRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.IsChirpyRed,
	)
	return i, err
}
